# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 671d7a6d3fdbe01f38193544cc2777ec4bbd155130cccbef96ba1abf9b80cdcddf76d3a8656ab8850f0f8d3b5a28514a740929131b2cccab172088cdcea0568b

test:
  secret_key_base: c3b1d7157f0701ef9ac6b7c299faacf3c19f33ebb4197479a980905ad4665ba3553b900342c4bbb8512480f63b4e406b94597e7be8a12c2c1a74d04b6008fc39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
